baseURL = 'https://guides.spatiosoft.com/overview-of-software-development/'
languageCode = 'en-us'
title = 'Overview Of Software Development | SPATIOSOFT'
theme = 'hugo-theme-relearn'
publishDir =  'overview-of-software-development'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
